---
title: "Simulating Data for Lab 6"
author: "Cory Costello"
date: "2/13/2020"
output: html_document
---

```{r}
library(rio)
library(tidyverse)
library(broom)
```

```{r}
df <- import("https://raw.githubusercontent.com/uopsych/psy612/master/labs/lab-2/data/PSY612_Lab2_Data.csv") %>% 
  janitor::clean_names() # to get things into snake_case
```

# Heteroscedastic data
```{r}
set.seed(1239813)
df_het <- df %>% 
  select(extraversion, happiness) %>% 
  mutate(., happiness = happiness + round(rnorm(147, 0, df$extraversion*.5), 2))
  
export(df_het, "../data/df_het.csv")
```

# Multi-colinear data

```{r}
set.seed(1239813)
df_mc <- df %>% 
  select(extraversion, happiness) %>% 
  mutate(., social_engagement = extraversion + round(rnorm(147, mean = 10, sd = 5), 0))
  
export(df_mc, "../data/df_mc.csv")
```

# Non-normal error

```{r}
df_nne <- df %>% 
  select(extraversion, happiness)  %>% 
  mutate(., happiness = happiness + rlnorm(147, sdlog = 1.85))
export(df_nne, "../data/df_nne.csv")
```

